const { DataTypes } = require('sequelize');
const { sequelize } = require('../common/sequelize');

const User = sequelize.define('User', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  uid: { type: DataTypes.STRING },
  login_type: { type: DataTypes.STRING },
  login_type_id: { type: DataTypes.STRING },
  name: { type: DataTypes.STRING, allowNull: true },
  email: { type: DataTypes.STRING, allowNull: true },
  profile_picture: { type: DataTypes.STRING, allowNull: true },
  subscribed_email: { type: DataTypes.STRING, allowNull: true },
  wallet_balance: { type: DataTypes.DECIMAL(10, 2), defaultValue: 0 },
  coin_balance: { type: DataTypes.DECIMAL(10, 2), defaultValue: 0 },
  language_id: { type: DataTypes.INTEGER, defaultValue: 1 },
  invited_id: { type: DataTypes.INTEGER, allowNull: true },
  is_weekly_vip: { type: DataTypes.INTEGER, defaultValue: 0 },
  weekly_vip_ended: { type: DataTypes.DATE, allowNull: true },
  is_yearly_vip: { type: DataTypes.INTEGER, defaultValue: 0 },
  yearly_vip_ended: { type: DataTypes.DATE, allowNull: true },
  extra_daily: { type: DataTypes.INTEGER, defaultValue: 0 },
  daily_watched_ads: { type: DataTypes.INTEGER, defaultValue: 0 },
  checked_in_day_1: { type: DataTypes.DATE, allowNull: true },
  checked_in_day_2: { type: DataTypes.DATE, allowNull: true },
  checked_in_day_3: { type: DataTypes.DATE, allowNull: true },
  checked_in_day_4: { type: DataTypes.DATE, allowNull: true },
  checked_in_day_5: { type: DataTypes.DATE, allowNull: true },
  checked_in_day_6: { type: DataTypes.DATE, allowNull: true },
  checked_in_day_7: { type: DataTypes.DATE, allowNull: true },
  login_reward: { type: DataTypes.INTEGER, defaultValue: 0 },
  bind_email: { type: DataTypes.INTEGER, defaultValue: 0 },
  link_whatsapp: { type: DataTypes.INTEGER, defaultValue: 0 },
  follow_us_on_facebook: { type: DataTypes.INTEGER, defaultValue: 0 },
  follow_us_on_instagram: { type: DataTypes.INTEGER, defaultValue: 0 },
  follow_us_on_youtube: { type: DataTypes.INTEGER, defaultValue: 0 },
  turn_on_notification: { type: DataTypes.INTEGER, defaultValue: 0 },
  is_deleted: { type: DataTypes.INTEGER, defaultValue: 0 },
  is_blocked: { type: DataTypes.INTEGER, defaultValue: 0 },
  is_picture_and_picture: { type: DataTypes.INTEGER, defaultValue: 0 },
  device_token: { type: DataTypes.TEXT, allowNull: true },
  device_id: { type: DataTypes.STRING, allowNull: true },
  notification_allowed: { type: DataTypes.INTEGER, defaultValue: 1 },
}, {
  tableName: 'users',
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at',
});

module.exports = User;
